name: nf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy==1.26.4
      - pandas==2.2.3
      - matplotlib
      - joblib==1.4.2
      - xgboost==2.1.3
      - scikit-learn==1.6.1
      - statsforecast==2.0.1
      - statsmodels==0.14.4
      - stack_data==0.6.2
